Script started on 2023-05-17 16:09:39+0700
./main_hse_insample.sh: line 4: /root/anaconda3/bin/activate: Permission denied
./main_hse_insample.sh: line 7: cd: /opt/python-da-2022V2b/skk_analytics/hse/insample/: No such file or directory
python: can't open file 'incident_rate_monthly_cumulative_insample.py': [Errno 2] No such file or directory
python: can't open file 'yearly_incident_rate_insample.py': [Errno 2] No such file or directory
./main_hse_insample.sh: line 12: /root/anaconda3/bin/deactivate: Permission denied

real	0m0,031s
user	0m0,027s
sys	0m0,004s

Script done on 2023-05-17 16:09:39+0700
